# Assignment 3 (Hypothesis Testing Exercise)

### Q.1 Minitab File : Cutlets.mtw

In [1]:
# H0: mu=mu2
# H1: mu1!=mu2

In [2]:
import pandas as pd
from scipy import stats

In [3]:
df=pd.read_csv(r"\Users\rajes\Downloads\Cutlets.csv")

In [4]:
unita=df['Unit A']

In [5]:
unitb=df['Unit B']

In [6]:
stats.ttest_ind(unita,unitb)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [7]:
# pvalue>0.05 then accept null hypothesis

### Q.2 Minitab File : LabTAT.mtw

In [8]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [9]:
# load the dataset
data=pd.read_csv(r"\Users\rajes\Downloads\LabTAT.csv")
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [10]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [11]:
p_value[1]  # compare it with α = 0.05

2.1156708949992414e-57

### Q.3 Buyer Ratio

In [18]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [19]:
# load the dataset
data=pd.read_csv(r"\Users\rajes\Downloads\BuyerRatio.csv")
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [20]:
# Make dimensional array
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [21]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [22]:
# Compare p_value with α = 0.05

In [23]:
# pvalue>0.05 then accept null hypothesis

### Q.4 Minitab File: CustomerOrderForm.mtw

In [24]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [25]:
# load the dataset
data=pd.read_csv(r"\Users\rajes\Downloads\Costomer+OrderForm.csv")
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [26]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [27]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [28]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [29]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [30]:
# Make a contingency table
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [31]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [32]:
# Compare p_value with α = 0.05

In [33]:
# pvalue<0.05 then reject alternative hypothesis